import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Navbar03, Navbar03NavItem, Navbar03Props} from "@/components/ui/shadcn-io/navbar-03";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navigationLinks: Navbar03NavItem[] = [
  {
    href:"/",
    label:"Home",
  },
  {
    href:"/about",
    label:"About us",
  },
  {
    href:"/events",
    label:"Events",
  },
  {
    href:"/research_projects",
    label:"Research Projects",
  },
  {
    href:"/publications",
    label:"Publications",
  },
  {
    href:"/join",
    label:"Join us",
  },
  {
    href:"/contact",
    label:"Contact us",
  },
]
const NavBarProps: Navbar03Props = {
  logoHref: "/",
  navigationLinks: navigationLinks,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={""}
      >
      <nav>
          <Navbar03
              logoHref={"/"}
              navigationLinks={navigationLinks}


          />
      </nav>
        {children}
      </body>
    </html>
  );
}
